<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MauriPDF.Core/MauriPDF.Core.csproj" />
    <ProjectReference Include="../MauriPDF.Rendering/MauriPDF.Rendering.csproj" />
    <ProjectReference Include="../MauriPDF.Editing/MauriPDF.Editing.csproj" />
    <ProjectReference Include="../MauriPDF.Infrastructure/MauriPDF.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../THIRD-PARTY-NOTICES.md" Link="THIRD-PARTY-NOTICES.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
