<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFiumCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MauriPDF.Core/MauriPDF.Core.csproj" />
    <ProjectReference Include="../MauriPDF.Pdfium/MauriPDF.Pdfium.csproj" />
  </ItemGroup>
</Project>
